name: Blynk Control Action

on:
  repository_dispatch:
    types: [trigger-blynk-action]  # Kích hoạt khi IFTTT gửi sự kiện

jobs:
  create-gist-and-send-request:
    runs-on: ubuntu-latest  # Chạy trên môi trường Ubuntu
    
    steps:
    # Bước 1: Tạo Gist với nội dung kích hoạt Blynk API
    - name: Create a Gist to trigger Blynk
      uses: actions/create-gist@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}  # Sử dụng GitHub token
        description: "Trigger Blynk API Action"
        public: true
        files: |
          blynk_request.txt: |
            Trigger Blynk API via GitHub Action.

    # Bước 2: Gửi HTTP request tới Blynk API
    - name: Send HTTP request to Blynk API
      run: |
        curl -X GET \
          'https://sgp1.blynk.cloud/external/api/update?token=_mJgeC6_YxnwyQ01qhqSXoAWu6P9ryIQ&v1=90'
